USE SERV_STORE;

CREATE DATABASE IF NOT EXISTS SERV_STORE;

CREATE TABLE IF NOT EXISTS SERV_STORE.USERS(
	ID BIGINT AUTO_INCREMENT,
	NAME VARCHAR(50),
	LAST_NAME VARCHAR(50),
	LOGIN VARCHAR(50) UNIQUE NOT NULL,
	EMAIL VARCHAR(100) UNIQUE NOT NULL,
	PWD VARCHAR(30) NOT NULL,
	CONSTRAINT PK_USERS PRIMARY KEY (ID)
)

CREATE TABLE IF NOT EXISTS SERV_STORE.S_SERVICE(
	ID BIGINT AUTO_INCREMENT,
	CAPTION VARCHAR(100) UNIQUE NOT NULL,
	CATEGORY VARCHAR(100) NOT NULL,
	DESCRIPTION TEXT NOT NULL,
	PRICE FLOAT NOT NULL,
	CONSTRAINT PK_SERVICE PRIMARY KEY (ID)
)

CREATE TABLE IF NOT EXISTS SERV_STORE.U_ORDER(
	ID BIGINT AUTO_INCREMENT,
	ID_USER BIGINT NOT NULL,
	ID_SERVICE BIGINT NOT NULL,
	ORDER_DATE DATE NOT NULL,
	STATUS VARCHAR(50) NOT NULL,
	CONSTRAINT PK_ORDER PRIMARY KEY (ID),
	CONSTRAINT FK1_ORDER_USER FOREIGN KEY (ID_USER) REFERENCES SERV_STORE.USERS(ID),
	CONSTRAINT FK2_ORDER_SERVICE FOREIGN KEY (ID_SERVICE) REFERENCES SERV_STORE.S_SERVICE(ID)
)

INSERT INTO SERV_STORE.USERS 
VALUES(
0,'VALERY', 'POPOV', 'FLAMMENWERFER', 'LEAVEMEALONE@GMAIL.COM', 'SOMEBODYTOLDME'
),
(0,'TESTY', '', 'NOMERCY', 'ADORABLEGUY@YANDEX.RU', 'TST')
;

INSERT INTO SERV_STORE.S_SERVICE 
VALUES
(0, 'MONITOR REPAIR', 'MONITORS', 'REPAIRING MONITORS ACTIVITY', 4000),
(0, 'PK DIAGNOSTICS', 'GENERAL', 'GENERAL COMPUTER DIAGNOSTICS ACTIVITY', 1500);

INSERT INTO SERV_STORE.U_ORDER
VALUES
(0, 1, 2, '2010-11-20', 'DONE');

ALTER TABLE SERV_STORE.USERS RENAME SERV_STORE.USER;
ALTER TABLE SERV_STORE.U_ORDER RENAME SERV_STORE.ORDER; 
ALTER TABLE `ORDER` ADD KEY `K1_DATE`(`ORDER_DATE`) ;
ALTER TABLE `USER` ADD KEY `K1_NAME` (`NAME`), ADD KEY `K2_LAST_NAME` (`LAST_NAME`), ADD KEY `K3_LOGIN` (`LOGIN`);

