version: '2.4'

services:
  my_db-node-01:
    build:
      context: ./
      dockerfile: mariadb/Dockerfile
    container_name: my_db-node-01
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: serv_store
      MYSQL_USER: myyuser
      MYSQL_PASSWORD: 123
      MYSQL_ROOT_PASSWORD: '1'
    command: >
      --sql-mode='STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION'
      --general-log=ON
      --log-queries-not-using-indexes=ON
    networks:
      - arch_network
    ports:
      - 3360:3306
    healthcheck:
      test: "/usr/bin/mysql --user=myyuser --password=123 --execute \"SHOW DATABASES;\""
      timeout: 20s
      retries: 5
    volumes:
      - my_db-node-01-data:/var/lib/mysql

  user_service:
    build:
      context: ./
      dockerfile: user/Dockerfile
    container_name: user_service
    environment:
      - DB_HOST=my_db-node-01
      - DB_PORT=3306
      - DB_LOGIN=myyuser
      - DB_PASSWORD=123
      - DB_DATABASE=serv_store
    ports:
      - 8082:8082
    networks:
      - arch_network
    depends_on:
      my_db-node-01:
        condition: service_healthy
  
  serving_service:
    build:
      context: ./
      dockerfile: service/Dockerfile
    container_name: serving_service
    environment:
      - DB_HOST=my_db-node-01
      - DB_PORT=3306
      - DB_LOGIN=myyuser
      - DB_PASSWORD=123
      - DB_DATABASE=serv_store
    ports:
      - 8083:8083
    networks:
      - arch_network
    depends_on:
      my_db-node-01:
        condition: service_healthy
  
  order_service:
    build:
      context: ./
      dockerfile: order/Dockerfile
    container_name: order_service
    environment:
      - DB_HOST=my_db-node-01
      - DB_PORT=3306
      - DB_LOGIN=myyuser
      - DB_PASSWORD=123
      - DB_DATABASE=serv_store
    ports:
      - 8084:8084
    networks:
      - arch_network
    depends_on:
      my_db-node-01:
        condition: service_healthy

volumes:
  my_db-node-01-data:

networks:
  arch_network:
    driver: "bridge"
    external: false